Fix #521 - Re-enable NSP

diff --git a/recipe-server/bin/ci/lint b/recipe-server/bin/ci/lint
--- a/recipe-server/bin/ci/lint
+++ b/recipe-server/bin/ci/lint
@@ -11,7 +11,11 @@ echo "Linting Style files"
 bin/ci/docker-run.sh npm run lint:css
 
 echo "Checking JS package security"
-# NSP doesn't deal well with unreliable networks, so it produces too
-# many false positives. This lets us run it, but not fail builds.
-# TODO: Detect network problems distinct from security errors.
-bin/ci/docker-run.sh npm run lint:js-security || true
+# Disable automatic failure
+set +e
+# nsp uses exit code 1 for security problems
+bin/ci/docker-run.sh npm run lint:js-security
+if [[ $? -eq 1 ]]; then
+    exit 1
+fi
+set -e
